apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-eks
  region: us-east-2
nodeGroups:
   - name: ng1
     desiredCapacity: 1
     instanceType: t2.micro
     ssh:
        publicKeyName: labec2key
   - name: ng-mixed
     minSize: 0
     maxSize: 5
     instancesDistribution:
       maxPrice: 0.017
       instanceTypes: ["t3.small", "t3.medium"] # At least one instance type should be specified
       onDemandBaseCapacity: 0
       onDemandPercentageAboveBaseCapacity: 50
       spotInstancePools: 2     
     ssh:
         publicKeyName: labec2key
